### PR TITLE
Build apk with GH Actions

### LINKED ISSUE #46: Enable GH Actions to build APKs
Related to this question https://github.com/gtt-project/redmine_gtt_smash/issues/33 we could enable GH Actions to build APKs automatically.

Should work similar to https://github.com/ursci/hikagefinder-app/tree/master/.github/workflows

### PR DESCRIPTION
**Pull request by dkastl**
Fixes #46  .

Changes proposed in this pull request:
- Adds GH Actions to build APK

### CODE REVIEW

**Comment by moovida** [comment]
Hi @dkastl , does this work on tag creation? And does it place the apk in the releases? Is it also possible to create an IOS ipa?

This would be a nice to have also on the smash side. :-)

**Comment by dkastl** [comment]
Theoretically it should do, practically ... I don't know. 

For Android I have done it once for another simple Flutter app: https://github.com/ursci/hikagefinder-app/tree/master/.github/workflows 
It did the build as a test and for every tagged version it linked the APK in the release page.

As you see, my first attempt failed already ;-)
Well, it was probably too optimistic, that it works with the first try. But I will look at it again next week.

**Comment by moovida** [comment]
I see that it fails on pulling one of the github projects. If you rely on the latest smashlibs, then you can now use: flutter_map_marker_cluster: ^0.4.0
since it has been updated to null safety.
That should fix your build (at least for that error).

**Comment by dkastl** [comment]
Ah, thanks for the hint.
Well, I probably need to do this on a workday ...

**Comment by moovida** [comment]
I understand you. Have a nice weekend!

**Pull request closed without merging**
