### PR TITLE
Initial GTT version

### PR DESCRIPTION
**Pull request by dkastl**
Changes proposed in this pull request:
- Initial GTT version

### CODE REVIEW

**Comment by sanak** [comment]
@mbasa (CC: @dkastl)  
There was discussion to keep original example `tags.json` which is automatically created when `forms` directory is empty (#14), and currently we download GTT tags.json as another file name (`gtt_tags.json`), but for usability, mixing form contents is not good, so I will rename current `gtt_tags.json` to `tags.json` to overwrite original example `tags.json` in this branch.

**Comment by sanak** [comment]
@mbasa (CC: @dkastl)  
Well, I will do above `tags.json` overwrite on another branch.

**Comment by dkastl** [comment]
If it's not too much work, what about adding a checkbox to let the user override tags.json or use a new name. Or let the user define a prefix themselves and otherwise override tags.json

**Comment by sanak** [comment]
@dkastl (CC: @mbasa)  
Well, in case of overwriting original example `tags.json`, still application restart is necessary, because `smashlibs` side `TagsManager.readFileTags()` is append only.

I will check whether current is no problem.

Also, I will rebase and force push this branch before merging this branch to `gtt/main`.
(At least, 1st - 3rd commits are not for GTT ones, but for internationalization ones, so those needs to be dropped from this branch.)

**Comment by sanak** [comment]
@dkastl (CC: @mbasa)  
Okay, I confirmed that the following operation works without problem, so I will merge this without adding any commits.
1. Start app
   - This generates original `tags.json` example, if `form` folder is empty.
2. Setting GTT
3. Import GTT
   - This downloads `gtt_tags.json`.
4. Exit app
5. Delete original `tags.json` example.
6. Start app
   - The app doesn't generate `tags.json` again.

About merge operation, I will try rebase on GitHub menu.

**Review by sanak — APPROVED** [review]
@dkastl (CC: @mbasa)  
As I mentioned in the comment, I will drop 1st - 3rd commits which are not for GTT during rebase merging process.

**Comment by sanak** [comment]
@mbasa  
Well, `pubspec.lock` and `pubspec.yaml` has conflict, so I will add fix commit (or drop unnecessary commits).
resolve_conflicts

**Comment by sanak** [comment]
@dkastl @mbasa-georepublic  
Hmm... Rebase doesn't work correctly, so I will rebase this branch to `gtt/main`, then push forcibly.  
(This means that `gr-develop` needs to be pulled again after reset back to quite before.)

**Comment by sanak** [comment]
Well, there are still format difference, so I will check it a bit on Android Studio...

**Comment by sanak** [comment]
Well, manual format changes are a bit tough work, so I checked the diffs by execute `flutter format <file>` command on both this branch and upstream master, then adjust import/export header import parts.
https://flutter.dev/docs/development/tools/formatting#automatically-formatting-code-with-the-flutter-command

Also, `gss_export.dart` modification seems to be happen accidentally, so I reverted it manually.

**Pull request merged**
